### ISSUE TITLE
Minimap: Elements that are children of the subject are in the wrong spot

### ISSUE THREAD

**Issue by bramus** [bramus/scroll-driven-animations-debugger-extension#30]
E.g. https://cdpn.io/pen/debug/bGORQMM/d1616ec346e06f09d7f34ec667571e2e _(forked from https://codepen.io/raphaelgoetter/pen/wvReGKK by @raphaelgoetter to preserve a copy)_

The element should be a child of the Subject.

**Comment by raphaelgoetter** [comment]
> The element should be a child of the Subject.

Aren't they? 

- the subject is the whole div who surrounds SVG (`.toppings`)
- the elementS are the 5 `path` descendants of `.toppings`

Am I mistaken? "descendants" should work too or must they be direct childs only? (the scroll-driven animation is working though)

**Comment by bramus** [comment]
> Aren't they?

In the DOM they are, but in the minimap they are rendered as siblings. That’s the bug.

**Comment by bramus** [comment]
Fix landed in in the code, but is pending release.

**Comment by bramus** [comment]
This fix is included in version 1.0.1 which was published today.
